spring:
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/Workspaces/playground/SpringCloud/configrepo
        encrypt:
          enabled: false
server:
  port: 8888
encrypt:
  key: globalecommerce1234
